#!/bin/bash 

# some more ls aliases
alias ll='ls -alFh'
alias la='ls -Ah'
alias less='less -r'       # raw control characters
alias vi=nvim
alias vim=nvim
alias ci=vi                # Common mistype with disasterous consequences.
alias grep='grep --color'  # show differences in colour
alias date='date "+%F"' 
alias tra='trash'
alias gpp='g++'
alias tp='trash-put'
alias tarp='tar --use-compress-program=pigz'
alias mcrypt='mcrypt -u'
alias rsync='rsync --progress'
alias qs='qstat -a'
alias dc='cd ..'
alias update="sudo apt-get update; sudo apt-get dist-upgrade -y ; sudo apt-get autoremove -y"
alias mod="module"
alias python='python3'
alias py='python3 -u'
alias pyvenv='source ~/.venv/bin/activate'

# git shortcuts.
alias gs='git status'
alias gc='git commit'
alias gp='git push'
alias ga='git add'
alias gd='git diff'

alias vipp='vi **/*.?pp'
alias vipy='vi **/*.py'
