#!/bin/bash
# NOTE: This all should be ported into modulefiles at some point!

source ~/tools/dotfiles/config/base_bashrc

# Add sources to path.
export PATH=${HOME}/tools/busempyer:$PATH
export PATH=${HOME}/tools:$PATH
export PATH=${HOME}/bin:$PATH
export PATH=.:$PATH
export PYTHONPATH=$PYTHONPATH:${HOME}/programs/pyWannier90/src
export PYTHONPATH=$PYTHONPATH:${HOME}/programs/pyscf
export PYTHONPATH=$PYTHONPATH:${HOME}/proj/bndefect
export PYTHONPATH=$PYTHONPATH:${HOME}/tools/busempyer
export PYTHONPATH=$PYTHONPATH:${HOME}/tools/misc
export PYTHONPATH=$PYTHONPATH:${HOME}/.local/lib/python3.7

export PYTHONPATH=$PYTHONPATH:${HOME}/programs/afqmclab/scripts

export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
