#!/bin/sh
# Shell customizations for bash or zsh. 

# Aliases.
alias ll='ls -alFh'
alias la='ls -Ah'
alias less='less -r'       # raw control characters
alias vi=nvim
alias vim=nvim
alias view='nvim -R'
alias ci=nvim # Common mistype with disasterous consequences.
alias grep='grep --color'  # show differences in colour
alias date='date "+%F"' 
alias gpp='g++'
alias tarp='tar --use-compress-program=pigz'
alias mcrypt='mcrypt -u'
alias rsync='rsync --progress'
alias dc='cd ..'
alias update="sudo apt-get update; sudo apt-get dist-upgrade -y ; sudo apt-get autoremove -y"
alias mod="module"
alias py="python -u"

# Git aliases.
alias gs='git status'
alias gc='git commit'
alias gp='git push'
alias ga='git add'
alias gd='git diff'

export MODULEPATH=${HOME}/soft/modulefiles:${MODULEPATH}

# Globus shortcuts.
gflat='c3dc2ae2-74c6-11e8-93bb-0a6d4e044368'
gsdsc='f327a108-b5cd-11e8-8241-0a3b7ca8ce66'

# active python venv
source ${HOME}/.venv/bin/activate
